-- ==========================================
-- FIX: Remove auth.users dependency for Single User Mode
-- Run this in Supabase SQL Editor
-- ==========================================

-- Step 1: Drop everything and start clean
DROP TABLE IF EXISTS public.usage_logs CASCADE;
DROP TABLE IF EXISTS public.exams CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Step 2: Create profiles WITHOUT referencing auth.users
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY,
  email text,
  full_name text,
  updated_at timestamp with time zone,
  settings jsonb DEFAULT '{"normal_limit": 60, "exam_start": null, "exam_end": null}'::jsonb
);

-- Step 3: Create usage_logs
CREATE TABLE public.usage_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) NOT NULL,
  date date DEFAULT current_date,
  youtube_mins int DEFAULT 0,
  instagram_mins int DEFAULT 0,
  UNIQUE(user_id, date)
);

-- Step 4: Create exams
CREATE TABLE public.exams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) NOT NULL,
  subject text NOT NULL,
  exam_date date NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Step 5: Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;

-- Step 6: Create OPEN policies (single user, no auth needed)
CREATE POLICY "allow_all_profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_usage" ON public.usage_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_exams" ON public.exams FOR ALL USING (true) WITH CHECK (true);

-- Step 7: Insert the single user
INSERT INTO public.profiles (id, email, full_name, settings)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'singleuser@focuslock.app',
    'Focus Master',
    '{"normal_limit": 1, "exam_start": null, "exam_end": null}'::jsonb
);
