-- ==========================================
-- 1. CLEANUP (Optional - be careful if you have data)
-- ==========================================
DROP TABLE IF EXISTS public.usage_logs;
DROP TABLE IF EXISTS public.exams;
DROP TABLE IF EXISTS public.profiles;

-- ==========================================
-- 2. CREATE TABLES
-- ==========================================

-- PROFILES
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  updated_at timestamp with time zone,
  settings jsonb default '{"normal_limit": 60, "exam_start": null, "exam_end": null}'::jsonb
);

-- USAGE LOGS
create table public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  date date default current_date,
  youtube_mins int default 0,
  instagram_mins int default 0,
  unique(user_id, date)
);

-- EXAMS
create table public.exams (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  subject text not null,
  exam_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ==========================================
-- 3. ENABLE RLS (Security)
-- ==========================================
alter table public.profiles enable row level security;
alter table public.usage_logs enable row level security;
alter table public.exams enable row level security;

-- ==========================================
-- 4. CREATE SINGLE USER (MASTER)
-- ==========================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = '00000000-0000-0000-0000-000000000001') THEN
        INSERT INTO auth.users (id, email)
        VALUES ('00000000-0000-0000-0000-000000000001', 'singleuser@focuslock.app');
    END IF;
END $$;

INSERT INTO public.profiles (id, email, full_name, settings)
VALUES (
    '00000000-0000-0000-0000-000000000001', 
    'singleuser@focuslock.app', 
    'Focus Master',
    '{"normal_limit": 60, "exam_start": null, "exam_end": null}'::jsonb
)
ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- 5. OPEN PUBLIC ACCESS (SINGLE USER MODE)
-- ==========================================
-- Allow anyone with the API key to Read/Write
CREATE POLICY "Public Read Profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Public Update Profiles" ON public.profiles FOR UPDATE USING (true);

CREATE POLICY "Public Read Usage" ON public.usage_logs FOR SELECT USING (true);
CREATE POLICY "Public Insert Usage" ON public.usage_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Usage" ON public.usage_logs FOR UPDATE USING (true);

CREATE POLICY "Public Read Exams" ON public.exams FOR SELECT USING (true);
CREATE POLICY "Public Insert Exams" ON public.exams FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Delete Exams" ON public.exams FOR DELETE USING (true);

-- ==========================================
-- 6. SETUP UTILS
-- ==========================================
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;
