-- 1. PROFILES TABLE (Extends Auth)
create table public.profiles (
  id uuid references auth.users not null,
  email text,
  full_name text,
  updated_at timestamp with time zone,
  
  -- FocusLock Specifics
  settings jsonb default '{"normal_limit": 60, "exam_start": null, "exam_end": null}'::jsonb,
  
  primary key (id)
);

-- 2. USAGE LOGS TABLE
create table public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  date date default current_date, -- 'YYYY-MM-DD'
  
  youtube_mins int default 0,
  instagram_mins int default 0,
  
  unique(user_id, date) -- One record per user per day
);

-- 3. EXAMS TABLE
create table public.exams (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  subject text not null,
  exam_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.usage_logs enable row level security;
alter table public.exams enable row level security;

-- Policies: Users can only see/edit their OWN data
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

create policy "Users can view own usage" on public.usage_logs for select using (auth.uid() = user_id);
create policy "Users can insert own usage" on public.usage_logs for insert with check (auth.uid() = user_id);
create policy "Users can update own usage" on public.usage_logs for update using (auth.uid() = user_id);

create policy "Users can view own exams" on public.exams for select using (auth.uid() = user_id);
create policy "Users can insert own exams" on public.exams for insert with check (auth.uid() = user_id);
create policy "Users can delete own exams" on public.exams for delete using (auth.uid() = user_id);

-- 5. FUNCTION TO HANDLE NEW USER SIGNUP
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function on auth.users insert
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
